#
#        .__
#  _____ |  |
# /     \|  |      MenuLobby - By Parsa
#|  Y Y  \  |__
#|__|_|  /____/    Thanks for downloading
#      \/
#

#  Welcome message that is welcome %playername%
Welcome-Messages: false
Welcome-Titles: true

# ScoreBoard
ScoreBoard:
  # You can disable it because many plugins need the scoreboard & the score board is beta
  enabled: true
  # Server ip your server ip for scoreboard
  server-ip: "yourserver.com"
  # The menu title, its the title for score board
  menu-title: "Lobby"
  # the menu title if plugin bedwars1058 enabled
  bedwars-title: "Bedwars Lobby"
  # i'am no sure this will work
  showplayers: false # This part is still in alpha and enabling is not recommended
# Achivments like when a player join the server for first time
achievements: true
# You know...
BossBar:
  # This is beta and may have some bugs
  enabled: true
  # message on bossbar
  message: "You Are Playing On YourServer.com"


#----------
support:
  discord: "https://example.com/discord"
  website: "https://example.com"
  store: "https://store.example.com"
warn:
  cheat: "you got 1 warn reason: cheat"
  toxic: "you got 1 warn reason: toxicity"
  crossteaming: "you got 1 warn reason: crossteaming / teamuping"
webhooks:
  #discord server webhooks
  enabled: true
  url: "https://discord.com/api/webhooks/WEBHOOK_ID/WEBHOOK_TOKEN"