name: MenuLobby
version: '${project.version}'
main: me.parsa.menulobby.MenuLobby
depend:
  - NoBlocks
commands:
  m:
    description: /<command>
    aliases:
      - ml
      - menulobby
  mtest:
    description: TEST
    usage: /<command>
  testkill:
    description: "testcmd"
    usage: /<command>
  mfly:
    description: "Just Turn On fly"
    usage: /<command>
  mmembers:
    description: Open a gui
    usage: /<command>
permissions:
  menulobby.admin:
    description: The admin remember this doesn't add all perms that fly and... have
    default: op
  menulobby.fly:
    description: Allows Flying.
    default: op
  menulobby.flyothers:
    description: Add fly for people
    default: op
  menulobby.ban:
    description: Ban
    default: op