name: MenuLobby
version: '${project.version}'
main: me.parsa.menulobby.MenuLobby
depend:
  - NoBlocks
commands:
  msupport:
    description: Opens a gui for support menu
    usage: /msupport
    aliases:
      - discord
      - site
      - website
      - store
      - ranks
      - support
  mgms:
    description: Changes your gamemode to survival
    usage: /mgms <user(optional)>
    aliases:
      - gms
  mgmc:
    description: Changes your gamemode to creative
    usage: /mgmc <user(optional)>
    aliases:
      - gmc
  msettings:
    description: Test4
    aliases:
      - admin
      - settings
  mkick:
    description: test2
  munban:
    description: TEST
  m:
    description: /<command>
    aliases:
      - ml
      - menulobby
  mreload:
    description: Reloads the plugin
    usage: /mreload
  mtest:
    description: TEST
    usage: /<command>
  testkill:
    description: "testcmd"
    usage: /<command>
  mfly:
    description: "Just Turn On fly"
    usage: /<command>
  mmembers:
    description: Open a gui
    usage: /<command>
permissions:
  menulobby.gms:
    description: Allows to change game-modes to survival
  menulobby.unban:
    description: Alows to unban users
  menulobby.admin:
    description: The admin remember this doesn't add all perms that fly and... have
    default: op
  menulobby.gm:
    description: Change gamemodes
    default: op
  menulobby.fly:
    description: Allows Flying.
    default: op
  menulobby.flyothers:
    description: Add fly for people
    default: op
  menulobby.ban:
    description: Ban
    default: op